FoodOrganicShop_NET/WebShop/Areas/Admin/Controllers/AdminAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebShop.Areas.Admin.Models;
using WebShop.Extension;
using WebShop.Models;
namespace WebShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AdminAccountsController : Controller
    {
        private readonly dbMarketsContext _context;
        public INotyfService _notyfService { get; }
        public AdminAccountsController(dbMarketsContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }
        public async Task<IActionResult> Index()
        {
            ViewData["QuyenTruyCap"] = new SelectList(_context.Roles, "RoleId", "Description");
            List<SelectListItem> lsTrangThai = new List<SelectListItem>();
            lsTrangThai.Add(new SelectListItem() { Text = "Hoạt động", Value = "1" });
            lsTrangThai.Add(new SelectListItem() { Text = "Khóa", Value = "0" });
            ViewData["lsTrangThai"] = lsTrangThai;
            var dbMarketsContext = _context.Accounts.Include(a => a.Role);
            return View(await dbMarketsContext.ToListAsync());
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();
            var account = await _context.Accounts.Include(a => a.Role).FirstOrDefaultAsync(m => m.AccountId == id);
            if (account == null) return NotFound();
            return View(account);
        }
        public IActionResult Create()
        {
            ViewData["QuyenTruyCap"] = new SelectList(_context.Roles, "RoleId", "RoleName");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AccountId,Phone,Email,Password,Salt,Active,FullName,RoleId,LastLogin,CreateDate")] Account account)
        {
            if (ModelState.IsValid)
            {
                _context.Add(account);
                await _context.SaveChangesAsync();
                _notyfService.Success("Tạo mới tài khoản thành công");
                return RedirectToAction(nameof(Index));
            }
            ViewData["QuyenTruyCap"] = new SelectList(_context.Roles, "RoleId", "RoleName", account.RoleId);
            return View(account);
        }
        public IActionResult ChangePassword()
        {
            ViewData["QuyenTruyCap"] = new SelectList(_context.Roles, "RoleId", "RoleName");
            return View();
        }
        [HttpPost]
        public IActionResult ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var taikhoan = _context.Accounts.AsNoTracking().SingleOrDefault(x => x.Email == model.Email);
                if (taikhoan == null) return RedirectToAction("Login", "Accounts");
                var pass = (model.PasswordNow.Trim() + taikhoan.Salt.Trim()).ToMD5();
                {
                    string passnew = (model.Password.Trim() + taikhoan.Salt.Trim()).ToMD5();
                    taikhoan.Password = passnew;
                    taikhoan.LastLogin = DateTime.Now;
                    _context.Update(taikhoan);
                    _context.SaveChanges();
                    _notyfService.Success("Đổi mật khẩu thành công");
                    return RedirectToAction("Login", "Accounts", new { Area = "Admin" });
                }
            }
            return View();
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            var account = await _context.Accounts.FindAsync(id);
            if (account == null) return NotFound();
            ViewData["QuyenTruyCap"] = new SelectList(_context.Roles, "RoleId", "RoleName", account.RoleId);
            return View(account);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AccountId,Phone,Email,Password,Salt,Active,FullName,RoleId,LastLogin,CreateDate")] Account account)
        {
            if (id != account.AccountId) return NotFound();
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(account);
                    await _context.SaveChangesAsync();
                }
                catch 
                {
                    if (!AccountExists(account.AccountId)) return NotFound();
                    else throw;
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["QuyenTruyCap"] = new SelectList(_context.Roles, "RoleId", "RoleName", account.RoleId);
            return View(account);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            var account = await _context.Accounts.Include(a => a.Role).FirstOrDefaultAsync(m => m.AccountId == id);
            if (account == null) return NotFound();
            return View(account);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var account = await _context.Accounts.FindAsync(id);
            _context.Accounts.Remove(account);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private bool AccountExists(int id)
        {
            return _context.Accounts.Any(e => e.AccountId == id);
        }
    }
}

FoodOrganicShop_NET/WebShop/Areas/Admin/Views/AdminAccounts/Create.cshtml
@model WebShop.Models.Account
@{
    ViewData["Title"] = "Tạo mới tài khoản quản trị";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="card-body">
    <h4>Tạo mới tài khoản quản trị</h4>
    <div class="m-t-25" style="max-width: 700px">
        <form asp-controller="AdminAccounts" asp-action="Create" method="post">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputEmail4">Họ và tên</label>
                    <input type="text" class="form-control" asp-for="FullName" placeholder="Họ và tên">
                </div>
                <div class="form-group col-md-6">
                    <label for="inputPassword4">Số điện thoại</label>
                    <input type="text" class="form-control" asp-for="Phone" placeholder="Số điện thoại">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputEmail4">Email</label>
                    <input type="text" class="form-control" asp-for="Email" placeholder="Email">
                </div>
                <div class="form-group col-md-6">
                    <label for="inputEmail4">Mật khẩu</label>
                    <input type="text" class="form-control" asp-for="Password" placeholder="Mật khẩu">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputPassword4">Quyền truy cập</label>
                    <select class="form-control" asp-for="RoleId" asp-items="@ViewBag.QuyenTruyCap" required>
                        <option value="0" disabled selected>Chọn quyền truy cập</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <input asp-for="Active" type="checkbox">
                    <label for="Active">Active</label>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Tạo mới</button>
        </form>
    </div>
</div>

FoodOrganicShop_NET/WebShop/Areas/Admin/Views/AdminAccounts/Delete.cshtml
@model WebShop.Models.Account
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<h1>Delete</h1>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Account</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">@Html.DisplayNameFor(model => model.Phone)</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.Phone)</dd>
        <dt class = "col-sm-2">@Html.DisplayNameFor(model => model.Email)</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.Email)</dd>
        <dt class = "col-sm-2">@Html.DisplayNameFor(model => model.Password)</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.Password)</dd>
        <dt class = "col-sm-2">@Html.DisplayNameFor(model => model.Salt)</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.Salt)</dd>
        <dt class = "col-sm-2">@Html.DisplayNameFor(model => model.Active)</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.Active)</dd>
        <dt class = "col-sm-2">@Html.DisplayNameFor(model => model.FullName)</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.FullName)</dd>
        <dt class = "col-sm-2">@Html.DisplayNameFor(model => model.LastLogin)</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.LastLogin)</dd>
        <dt class = "col-sm-2">@Html.DisplayNameFor(model => model.CreateDate)</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.CreateDate)</dd>
        <dt class = "col-sm-2">@Html.DisplayNameFor(model => model.Role)</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.Role.RoleId)</dd class>
    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="AccountId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FoodOrganicShop_NET/WebShop/Areas/Admin/Views/AdminAccounts/Details.cshtml
@model WebShop.Models.Account
@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
	<div class="header-sub-title">
		<nav class="breadcrumb breadcrumb-dash">
			<a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
			<a asp-area="Admin" asp-controller="AdminAccounts" asp-action="Index" class="breadcrumb-item">Danh sách tài khoản</a>
			<span class="breadcrumb-item active">Thông tin tài khoản : @Model.FullName</span>
		</nav>
	</div>
</div>
<div class="card">
	<div class="card-body">
		<h1>Thông tin tài khoản</h1>
		<hr />
		<div class="table-responsive">
			<table class="product-info-table m-t-20">
				<tbody>
					<tr>
						<td class="card-title">ID:</td>
						<td class="text-dark font-weight-semibold">@Model.AccountId</td>
					</tr>
					<tr>
						<td class="card-title">Họ và tên</td>
						<td>@Model.FullName</td>
					</tr>
					<tr>
						<td class="card-title">Số điện thoại</td>
						<td><a href="tel:@Model.Phone">@Model.Phone</td>
					</tr>
					<tr>
						<td class="card-title">Email</td>
						<td><a href="mailto:@Model.Phone">@Model.Email</td>
					</tr>
					<tr>
						<td class="card-title">Ngày tạo</td>
						<td>@Model.CreateDate</td>
					</tr>
					<tr>
						<td class="card-title">Trạng thái:</td>
						<td>
							@if (Model.Active)
							{
								<div class="switch m-r-10">
									<input type="checkbox" id="switch-1" checked="" disabled />
									<label for="switch-1"></label>
								</div>
							}
							else
							{
								<div class="switch m-r-10">
									<input type="checkbox" id="switch-1" disabled />
									<label for="switch-1"></label>
								</div>
							}
						</td>
					</tr>
					<tr>
						<td class="card-title">Mật khẩu</td>
						<td>@Model.Password</td>
					</tr>
				</tbody>
			</table>
			<div class="m-b-15">
				<a class="btn btn-primary m-r-10" asp-action="Index"><i class="anticon anticon-rollback m-r-5"></i><span>Trở về</span></a>
				<a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminAccounts" asp-action="Edit" asp-route-id="@Model.AccountId"><i class="anticon anticon-edit m-r-5"></i><span>Chỉnh sửa</span></a>
			</div>
		</div>
	</div>
</div>

FoodOrganicShop_NET/WebShop/Areas/Admin/Views/AdminAccounts/Edit.cshtml
@model WebShop.Models.Account
@{
	ViewData["Title"] = "Edit";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
	<div class="header-sub-title">
		<nav class="breadcrumb breadcrumb-dash">
			<a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
			<a asp-area="Admin" asp-controller="AdminRoles" asp-action="Index" class="breadcrumb-item">Danh sách quyền truy cập</a>
			<span class="breadcrumb-item active">Chỉnh sửa quyền truy cập</span>
		</nav>
	</div>
</div>
<div class="card">
	<div class="card-body">
		<h1>Chỉnh sửa tài khoản</h1>
		<hr />
		<div class="row">
			<div class="col-md-4">
				<form asp-action="Edit">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>
					<input type="hidden" asp-for="AccountId" />
					<div class="form-group">
						<label asp-for="FullName" class="control-label  card-title">Họ và tên</label>
						<input asp-for="FullName" class="form-control" required/>
						<span asp-validation-for="FullName" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="RoleId" class="control-label  card-title">Quyền truy cập</label>
						<select class="form-control" asp-for="RoleId" asp-items="@ViewBag.QuyenTruyCap" required>
							<option value="0" disabled selected>Chọn quyền truy cập</option>
						</select>
						<span asp-validation-for="RoleId" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="Phone" class="control-label  card-title">Số điện thoại</label>
						<input asp-for="Phone" class="form-control" required/>
						<span asp-validation-for="Phone" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="Email" class="control-label  card-title"></label>
						<input asp-for="Email" class="form-control" required />
						<span asp-validation-for="Email" class="text-danger"></span>
					</div>
					<div class="form-group form-check">
						<label class="form-check-label">
							<input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
						</label>
					</div>
					<div class="form-group">
						<label asp-for="CreateDate" class="control-label card-title">Ngày tạo</label>
						<input asp-for="CreateDate" class="form-control" required />
						<span asp-validation-for="CreateDate" class="text-danger"></span>
					</div>
					<div class="form-group">
						<div>
							<button type="submit" class="btn btn-primary m-r-10">
								<i class="anticon anticon-save m-r-5"></i><span>Lưu</span>
							</button>
							<a class="btn btn-primary m-r-10" asp-action="Index"><i class="anticon anticon-rollback m-r-5"></i>Trở về<span></span></a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

FoodOrganicShop_NET/WebShop/Areas/Admin/Views/AdminAccounts/Index.cshtml
@model IEnumerable<WebShop.Models.Account>
@{
	ViewData["Title"] = "Danh sách tài khoản quản trị";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
	<div class="header-sub-title">
		<nav class="breadcrumb breadcrumb-dash">
			<a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
			<span class="breadcrumb-item active">Danh sách tài khoản</span>
		</nav>
	</div>
</div>
<div class="card">
	<div class="card-body">
		<h1>Danh sách tài khoản</h1>
		<hr />
		<div class="row m-b-30">
			<div class="col-lg-8"><div class="d-md-flex"></div></div>
			<div class="col-lg-4 text-right">
				<a class="btn btn-primary" asp-area="Admin" asp-controller="AdminAccounts" asp-action="Create"><i class="anticon anticon-plus-circle m-r-5"></i><span>Thêm mới tài khoản</span></a>
			</div>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table table-hover e-commerce-table">
			<thead>
				<tr>
					<th>ID</th>
					<th>Họ và tên</th>
					<th>Email</th>
					<th>Điện thoại</th>
					<th>Quyền truy cập</th>
					<th>Trạng thái</th>
					<th>Thao tác</th>
				</tr>
			</thead>
			<tbody>
				@if (Model != null)
				{
					foreach (var item in Model)
					{
						<tr>
							<td>@item.AccountId</td>
							<td>
								<div class="d-flex align-items-center">
									<img class="img-fluid rounded" src="assets/images/others/thumb-9.jpg" style="max-width: 60px" alt="">
									<h6 class="m-b-0 m-l-10">@item.FullName</h6>
								</div>
							</td>
							<td><a href="mailto:@item.Email">@item.Email</a></td>
							<td><a href="tel:@item.Phone">@item.Phone</a></td>
							<td>@item.RoleId</td>
							<td>
								@if (item.Active)
								{
									<div class="d-flex align-items-center">
										<div class="badge badge-success badge-dot m-r-10"></div>
										<div>Hoạt động</div>
									</div>
								}
								else
								{
									<div class="d-flex align-items-center">
										<div class="badge badge-danger badge-dot m-r-10"></div>
										<div>Khóa</div>
									</div>
								}
							</td>
							<td>
								<a class="btn btn-info btn-tone m-r-5" asp-area="Admin" asp-controller="AdminAccounts" asp-action="Details" asp-route-id="@item.AccountId"><i class="anticon anticon-info-circle m-r-5"></i><span>Chi tiết</span></a>
								<a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminAccounts" asp-action="Edit" asp-route-id="@item.AccountId"><i class="anticon anticon-edit m-r-5"></i><span>Chỉnh sửa</span></a>
							</td>
						</tr>
					}
				}
			</tbody>
		</table>
	</div>
</div>