FoodOrganicShop_NET/WebShop/Areas/Admin/Controllers/AdminRolesController.cs
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebShop.Models;
namespace WebShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AdminRolesController : Controller
    {
        private readonly dbMarketsContext _context;
        public INotyfService _notyfService { get; }
        public AdminRolesController(dbMarketsContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _context.Roles.ToListAsync());
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();
            var role = await _context.Roles.FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null) return NotFound();
            return View(role);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RoleId,RoleName,Description")] Role role)
        {
            if (ModelState.IsValid)
            {
                while (true)
                {
                    try
                    {
                        if (RoleExists(role.RoleName))
                        {
                            _notyfService.Error("Quyền truy cập đã tồn tại");
                            break;
                        }
                        else
                        {
                            _context.Add(role);
                            await _context.SaveChangesAsync();
                            _notyfService.Success("Tạo mới quyền truy cập thành công");
                        }
                    }
                    catch { 
                        throw;
                    }
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(role);
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            var role = await _context.Roles.FindAsync(id);
            if (role == null) return NotFound();
            return View(role);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RoleId,RoleName,Description")] Role role)
		{
			if (id != role.RoleId) return NotFound();
			if (ModelState.IsValid)
			{
                while (true)
                {
                    try
                    {
						if (RoleExistsId(id, role.RoleName))
						{
							_context.Update(role);
							await _context.SaveChangesAsync();
							_notyfService.Success("Cập nhật thành công");
                        }
                        else
                        {
							if (RoleExists(role.RoleName))
							{
								_notyfService.Error("Quyền truy cập đã tồn tại");
								break;
							}
							else
							{
								_context.Update(role);
								await _context.SaveChangesAsync();
								_notyfService.Success("Cập nhật thành công");
							}
						}
					}
                    catch {
                        throw;
                    }
                    return RedirectToAction(nameof(Index));
                }
			}
			return View(role);
		}
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            var role = await _context.Roles.FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null) return NotFound();
            return View(role);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var role = await _context.Roles.FindAsync(id);
            _context.Roles.Remove(role);
            await _context.SaveChangesAsync();
            _notyfService.Success("Xóa quyền truy cập thành công");
            return RedirectToAction(nameof(Index));
        }
        private bool RoleExists(string name)
        {
            return _context.Roles.Any(e => e.RoleName == name);
        }
		private bool RoleExistsId(int id, string name)
		{
			return _context.Roles.Where(x => x.RoleId == id).Any(x=>x.RoleName==name);
		}
	}
}

FoodOrganicShop_NET/WebShop/Areas/Admin/Views/AdminRoles/Create.cshtml
@model WebShop.Models.Role
@{
	ViewData["Title"] = "Thêm quyền truy cập";
}
<div class="page-header">
	<div class="header-sub-title">
		<nav class="breadcrumb breadcrumb-dash">
			<a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
			<a asp-area="Admin" asp-controller="AdminRoles" asp-action="Index" class="breadcrumb-item">Danh sách quyền truy cập</a>
			<span class="breadcrumb-item active">Thêm quyền truy cập</span>
		</nav>
	</div>
</div>
<div class="card">
	<div class="card-body">
		<h1>Thêm quyền truy cập</h1>
		<hr />
		<div class="row">
			<div class="col-md-6">
				<form asp-action="Create">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>
					<div class="form-group">
						<label asp-for="RoleName" class="control-label card-title">Tên quyền truy cập</label>
						<input asp-for="RoleName" class="form-control" required />
						<span asp-validation-for="RoleName" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="Description" class="control-label card-title">Mô tả</label>
						<input asp-for="Description" class="form-control" required />
						<span asp-validation-for="Description" class="text-danger"></span>
					</div>
					<div class="form-group">
						<input type="submit" value="Thêm mới" class="btn btn-primary m-r-10" />
						<a class="btn btn-primary m-r-10" asp-action="Index">Trở về</a>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

FoodOrganicShop_NET/WebShop/Areas/Admin/Views/AdminRoles/Delete.cshtml
@model WebShop.Models.Role
@{
	ViewData["Title"] = "Xác nhận xóa quyền truy cập";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
	<div class="header-sub-title">
		<nav class="breadcrumb breadcrumb-dash">
			<a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
			<a asp-area="Admin" asp-controller="AdminRoles" asp-action="Index" class="breadcrumb-item ">Danh sách quyền truy cập</a>
			<span class="breadcrumb-item active">Xác nhận xóa quyền truy cập</span>
		</nav>
	</div>
</div>
<div class="card">
	<div class="card-body">
		<h1>Xác nhận xóa quyền truy cập</h1>
		<hr />
		<div class="col-md-6">
		<table class="product-info-table m-t-20 table-responsive">
			<tbody>
				<tr>
					<td class="card-title">ID:</td>
					<td class="text-dark font-weight-semibold">@Model.RoleId</td>
				</tr>
				<tr>
					<td class="card-title">Tên quyền truy cập:</td>
					<td>@Model.RoleName</td>
				</tr>
				<tr>
					<td class="card-title">Mô tả:</td>
					<td>@Model.Description</td>
				</tr>
				<tr>
					<td class="card-title">Xác nhận xóa:</td>
					<td>
						<form asp-action="Delete" asp-route-id="@Model.RoleId">
							<input type="hidden" asp-for="RoleId" />
							<input type="submit" value="Xác nhận xóa" class="btn btn-danger" />
						</form>
					</td>
				</tr>
			</tbody>
		</table>
		<div>
			<a class="btn btn-primary" asp-action="Index"><i class="anticon anticon-rollback m-r-5"></i><span>Trở về</span></a>
		</div>
	</div>
	</div>
</div>

FoodOrganicShop_NET/WebShop/Areas/Admin/Views/AdminRoles/Details.cshtml
@model WebShop.Models.Role
@{
	ViewData["Title"] = "Thông tin quyền truy cập";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
	<div class="header-sub-title">
		<nav class="breadcrumb breadcrumb-dash">
			<a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
			<a asp-area="Admin" asp-controller="AdminRoles" asp-action="Index" class="breadcrumb-item">Danh sách quyền truy cập</a>
			<span class="breadcrumb-item active">Thông tin quyền truy cập</span>
		</nav>
	</div>
</div>
<div class="card">
	<div class="card-body">
		<h1>Thông tin quyền truy cập</h1>
		<hr />
		<div class="col-md-6">
			<table class="product-info-table m-t-20">
				<tbody>
					<tr>
						<td class="card-title">ID:</td>
						<td class="text-dark font-weight-semibold">@Model.RoleId</td>
					</tr>
					<tr>
						<td class="card-title">Tên quyền truy cập:</td>
						<td>@Model.RoleName</td>
					</tr>
					<tr>
						<td class="card-title">Mô tả:</td>
						<td>@Model.Description</td>
					</tr>
				</tbody>
			</table>
			<div class="m-b-15">
				<a class="btn btn-primary m-r-10" asp-action="Index"><i class="anticon anticon-rollback m-r-5"></i><span>Trở về</span></a>
				<a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminRoles" asp-action="Edit" asp-route-id="@Model.RoleId"><i class="anticon anticon-edit m-r-5"></i><span>Chỉnh sửa</span></a>
			</div>
		</div>
	</div>
</div>

FoodOrganicShop_NET/WebShop/Areas/Admin/Views/AdminRoles/Edit.cshtml
@model WebShop.Models.Role
@{
	ViewData["Title"] = "Chỉnh sửa quyền truy cập";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
	<div class="header-sub-title">
		<nav class="breadcrumb breadcrumb-dash">
			<a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
			<a asp-area="Admin" asp-controller="AdminRoles" asp-action="Index" class="breadcrumb-item">Danh sách quyền truy cập</a>
			<span class="breadcrumb-item active">Chỉnh sửa quyền truy cập</span>
		</nav>
	</div>
</div>
<div class="card">
	<div class="card-body">
		<h1>Chỉnh sửa quyền truy cập</h1>
		<hr />
		<form asp-action="Edit" asp-route-id="@Model.RoleId" method="post">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="RoleId" />
			<div class="col-md-6">
				<div class="form-group">
					<label class="control-label card-title">Tên quyền truy cập</label>
					<div>
						<input type="text" class="form-control" asp-for="RoleName" placeholder="Tên quyền" required>
					</div>
				</div>
				<div class="form-group">
					<label class="control-label card-title">Mô tả</label>
					<div>
						<input type="text" class="form-control" asp-for="Description" placeholder="Mô tả" required>
					</div>
				</div>
				<div class="form-group">
					<div>
						<button type="submit" class="btn btn-primary m-r-10"><i class="anticon anticon-save m-r-5"></i><span>Lưu</span></button>
						<a class="btn btn-primary m-r-10" asp-action="Index"><i class="anticon anticon-rollback m-r-5"></i>Trở về<span></span></a>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>

FoodOrganicShop_NET/WebShop/Areas/Admin/Views/AdminRoles/Index.cshtml
@model IEnumerable<WebShop.Models.Role>
@{
	ViewData["Title"] = "Quản lý quyền truy cập";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
	<div class="header-sub-title">
		<nav class="breadcrumb breadcrumb-dash">
			<a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
			<span class="breadcrumb-item active">Danh sách quyền truy cập</span>
		</nav>
	</div>
</div>
<div class="card">
	<div class="card-body">
		<h1>Danh sách quyền truy cập</h1>
		<hr />
		<div class="row m-b-30">
			<div class="col-lg-8"><div class="d-md-flex"></div></div>
			<div class="col-lg-4 text-right">
				<a class="btn btn-primary" asp-area="Admin" asp-controller="AdminRoles" asp-action="Create"><i class="anticon anticon-plus-circle m-r-5"></i><span>Thêm mới</span></a>
			</div>
		</div>
		<div class="table-responsive">
			<table class="table table-hover e-commerce-table">
				<thead>
					<tr>
						<th scope="col">ID</th>
						<th scope="col">Tên</th>
						<th scope="col">Mô tả</th>
						<th scope="col">Thao tác</th>
					</tr>
				</thead>
				<tbody>
					@if (Model != null)
					{
						foreach (var item in Model)
						{
							<tr>
								<th scope="row">@item.RoleId</th>
								<td>@item.RoleName</td>
								<td>@item.Description</td>
								<td>
									<a class="btn btn-info btn-tone m-r-5" asp-area="Admin" asp-controller="AdminRoles" asp-action="Details" asp-route-id="@item.RoleId"><i class="anticon anticon-info-circle m-r-5"></i><span>Chi tiết</span></a>
									<a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminRoles" asp-action="Edit" asp-route-id="@item.RoleId"><i class="anticon anticon-edit m-r-5"></i><span>Chỉnh sửa</span></a>
									<a class="btn btn-danger btn-tone m-r-5" asp-area="Admin" asp-controller="AdminRoles" asp-action="Delete" asp-route-id="@item.RoleId"><i class="anticon anticon-delete m-r-5"></i><span>Xóa</span></a>
								</td>
							</tr>
						}
					}
				</tbody>
			</table>
		</div>
	</div>
</div>